---

- name: Verify
  hosts: mailserver
  vars:
    is_container: false
  pre_tasks:
    - name: RedHat | Ensure pgrep is present
      ansible.builtin.package:
        name: procps-ng
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8
    - name: RedHat | set packages to validate
      ansible.builtin.set_fact:
        verify_pkgs:
          - pypolicyd-spf
      when: ansible_facts['os_family'] == "RedHat"
    - name: Debian | Ensure pgrep is present
      ansible.builtin.package:
        name: procps
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    - name: Debian | set packages to validate
      ansible.builtin.set_fact:
        verify_pkgs:
          - postfix-policyd-spf-python
      when: ansible_facts['os_family'] == 'Debian'
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when:
        - ansible_facts['virtualization_type'] is defined
        - (ansible_facts['virtualization_type'] == "docker" or ansible_facts['virtualization_type'] == "containerd")
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that:
          - ansible_facts['facts'].packages[item] is defined
      with_items: "{{ verify_pkgs }}"

    - name: Ensure process is running
      ansible.builtin.command: pgrep -u root master
      register: ps
      changed_when: false
      ignore_errors: true
    - name: Validate ps output
      ansible.builtin.assert:
        that: ps.stdout | length > 0
      when:
        - not is_container | bool

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 25 }
      when:
        - not is_container | bool

    - name: Fetch content of /etc/postfix/main.cf
      ansible.builtin.slurp:
        src: /etc/postfix/main.cf
      register: cfg
    - name: Validate main.cf
      ansible.builtin.assert:
        that:
          - "'smtpd_banner = $myhostname ESMTP Sorry, No banner' in cfg['content'] | b64decode"
          - "'smtpd_tls_security_level = encrypt' in cfg['content'] | b64decode"

    - name: Postconf
      ansible.builtin.command: postconf
      changed_when: false
      register: postconf
    - name: Debian | Validate postconf
      ansible.builtin.assert:
        that:
          - "'smtpd_tls_security_level = encrypt' in postconf.stdout"
          - "'disable_vrfy_command = yes' in postconf.stdout"
          - "'warning: ' not in postconf.stderr"
          - "'fatal' not in postconf.stderr"
          - postconf.rc == 0
      when:
        - ansible_facts['os_family'] == "Debian"
    - name: RedHat | Validate postconf
      ansible.builtin.assert:
        that:
          - "'smtpd_tls_security_level = encrypt' in postconf.stdout"
          - "'disable_vrfy_command = yes' in postconf.stdout"
          # rockylinux-9: part "warning: ", part vars delay_warning_time, helpful_warnings daemon_table_open_error_is_fatal
          # - "'warning: ' not in postconf.stderr"
          # - "'fatal' not in postconf.stderr"
          - postconf.rc == 0
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: Ubuntu 20.04+ | Not container
      when:
        - (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 20) or
          (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] | int >= 12) or
          (ansible_facts['os_family'] == "RedHat" and not is_container)
      block:
        - name: Openssl s_client
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo | openssl s_client -starttls smtp -connect localhost:25
          args:
            executable: /bin/bash
          changed_when: false
          register: s_client
        - name: Validate openssl s_client
          ansible.builtin.assert:
            that:
              - "'CONNECTED(' in s_client.stdout"
              - "'SSL handshake has read' in s_client.stdout"
              - "'New, TLSv1.3, Cipher is' in s_client.stdout"
    - name: Ubuntu 18.04
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 18)
      block:
        - name: Focal | openssl s_client
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo | openssl s_client -starttls smtp -connect localhost:25
          args:
            executable: /bin/bash
          changed_when: false
          register: s_client
        - name: Focal | Validate openssl s_client
          ansible.builtin.assert:
            that:
              - "'/CONNECTED/' in s_client.stdout"
              - "'SSL handshake has read' in s_client.stdout"
              - "'New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384' in s_client.stdout"
    - name: Ubuntu 22.04+, Redhat not container
      when:
        - (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 22) or
          (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] | int >= 12) or
          (ansible_facts['os_family'] == "RedHat" and not is_container)
      block:
        - name: Openssl s_client - EDH
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo | timeout 15 openssl s_client -starttls smtp -connect localhost:25 -cipher "EDH"
          args:
            executable: /bin/bash
          changed_when: false
          register: s_client2
        - name: Validate openssl s_client - EDH
          ansible.builtin.assert:
            that:
              - "'CONNECTED(' in s_client2.stdout"
              - "'Peer signing digest: SHA256' in s_client2.stdout"
              # FIXME! present but not matched???
              # - "'Server Temp key: X25519, 253 bits' in s_client2.stdout"
              # - "'Server public key.*2048 bit' in s_client2.stdout"
    - name: Ubuntu 18.04 EDH
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 18)
      block:
        - name: Focal | openssl s_client - EDH
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo | timeout 15 openssl s_client -starttls smtp -connect localhost:25 -cipher "EDH"
          args:
            executable: /bin/bash
          changed_when: false
          register: s_client2
        - name: Focal | Validate openssl s_client - EDH
          ansible.builtin.assert:
            that:
              - "'/CONNECTED/' in s_client2.stdout"
              - "'Server Temp Key: X25519, 253 bits' in s_client2.stdout"
              - "'Server public key.*2048 bit' in s_client2.stdout"
